### ISSUE TITLE
Message format

### ISSUE THREAD

**Issue by tdx** [alphallc/redmine_xmpp_notifications#3]
Is it possible to format xmpp notifications like smtp notifications (wiki format etc) ?

**Comment by msva** [comment]
@tdx idea itself looks nice, but it seems nobody, who can add such functionality is either not interested, or have no amount time, needed for that.

Anyway, Pull Requests are welcome any time.

P.S. Maybe, someday I made it myself, but I'm in a deadline time with few current projects, so, I'd not counting on that.
